---
- hosts: all
  become: true
  tasks:
  - name: installApachehttpserver
    yum:
     name: httpd
     state: latest
  - name: copy index.html
    copy: 
      src: index.html
      dest: /var/www/html/index.html
  - name: startapacheserver
    service:
      name: httpd
      state: started
      enabled: true
...

