---
- hosts: all
  become: true 
  tasks:
   - name: Install git
     yum: 
      name: git
      state: present  
   - name: install httpd server
     yum: 
       name: httpd
       state: present 
   - name: install tree
     yum: 
       name: tree
       state: present 
   - name: install 
     yum: 
       name: unzip
       state: present 
...


