---
- hosts: all
  become: true
  vars: 
    companyName: Naveen
    location: sindhu
  tasks:
  - name: installApachehttpserver
    yum:
     name: httpd
     state: latest
  - name: startapacheserver
    service:
      name: httpd
      state: started
      enabled: true
  - name: Copyindex.html
    template:
      src: index.html
      dest: /var/www/html/index.html
...
